### ISSUE TITLE
Upgrade Docker MySQL to version 8+

### ISSUE THREAD

**Issue by mattdevio** [mattdevio/moolahlah#57]
Tried to upgrade Docker Mysql image to version 8 so I could use some new features. It works great; however, I can't connect to it from [Sequel Pro](https://github.com/sequelpro/sequelpro/releases) due to a bug which won't let the remote user authenticate.

The bug is Sequel Pro has been fixed in version 1.2 which has not been released yet. Once sequel pro v1.2 is updated, I will updated the docker image.

```yml
  mysqldb:
    image: mysql:8.0.13
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    container_name: "${MYSQL_HOST}"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./temp/mysql:/var/lib/mysql
    networks:
      - moolahlah-network
```
